name: CI/CD Full Pipeline

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to ECR
      id: ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Image
      run: docker build -t devops-app .

    - name: Tag Image
      run: |
        docker tag devops-app:latest \
        ${{ steps.ecr.outputs.registry }}/devops-app:latest

    - name: Push Image
      run: |
        docker push \
        ${{ steps.ecr.outputs.registry }}/devops-app:latest

    # 🔥 NEW STEP (AUTO DEPLOY)
    - name: Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER }} \
          --service ${{ secrets.ECS_SERVICE }} \
          --force-new-deployment